import mongoose from "mongoose";

export const addressSchema=new mongoose.Schema(
    {
        userId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
            required:true
        },
        title:{
            type:String,
            required:true
        },
        addressLine1:{
            type:String,
            required:true
        },
        addressLine2:{
            type:String
        },
        city:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
       postalCode:{
        type:String,
        required:true
    },
        mobile:{
            type:String,
            required:true
        },
       isDefault:{
        type:Boolean,
        default:false
    },
    createdAt:{
        type:Date,
        default:Date.now
    },
    updatedAt:{
        type:Date,
        default:Date.now
    }
    }
)
export default mongoose.model("Address",addressSchema)